application: frost-1001
version: v1

runtime: go
api_version: go1

# defeat all caching of static files during development
default_expiration: "0d 0h"

handlers:

- url: /static
  static_dir: ../../server/static
  application_readable: true # So the app can read and parse templates at runtime

- url: /.*
  script: _go_app
